unpackaged/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Company__c/fields/Highest_Salary__c.field-meta.xml
<CustomField>
    <fullName>Highest_Salary__c</fullName>
    <label>Highest Salary</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EmployeeTriggerHandler.cls
public class EmployeeTriggerHandler {
    public static void updateHighestSal(List<Employee__c> empList){
        Set<Id> companyIds = new Set<Id>();
        for(Employee__c emp: empList){
            companyIds.add(emp.Company__c);
        }
        
        List<Company__c> cmpListToupdate = [SELECT Id, Highest_Salary__c, (SELECT Id, Salary__c, Name FROM Employees__r ORDER BY Salary__C DESC LIMIT 2) FROM Company__c WHERE Id IN : companyIds];
        
        for(Company__c cmp : cmpListToUpdate){
            cmp.Highest_Salary__c = '';
            for(Employee__c emp: cmp.Employees__r){
                cmp.Highest_Salary__c += emp.Salary__c + ' ' + emp.Name + '\n';
            }
        }
        
        update cmpListToUpdate;
    }
}